### ISSUE TITLE
MarkerClusterer is not defined

### ISSUE THREAD

**Issue by eyalabadi98** [danielehrhardt/Ionic-2-Google-Maps-Marker-Cluster#6]
Hello,

I tried to recreate this app but im getting a markerCluster error

Here is the error:

```
Runtime Error
Uncaught (in promise): ReferenceError: MarkerClusterer is not defined ReferenceError: MarkerClusterer is not defined at http://localhost:8100/build/main.js:55759:17 at t.invoke (http://localhost:8100/build/polyfills.js:3:8488) at Object.onInvoke (http://localhost:8100/build/main.js:4403:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:8428) at r.run (http://localhost:8100/build/polyfills.js:3:3686) at NgZone.run (http://localhost:8100/build/main.js:4272:62) at HomePage.initializeMap (http://localhost:8100/build/main.js:55716:19) at HomePage.loadMaps (http://localhost:8100/build/main.js:55636:18) at http://localhost:8100/build/main.js:55616:63 at t.invoke (http://localhost:8100/build/polyfills.js:3:8488)
Stack
Error: Uncaught (in promise): ReferenceError: MarkerClusterer is not defined
ReferenceError: MarkerClusterer is not defined
    at http://localhost:8100/build/main.js:55759:17
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8488)
    at Object.onInvoke (http://localhost:8100/build/main.js:4403:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8428)
    at r.run (http://localhost:8100/build/polyfills.js:3:3686)
    at NgZone.run (http://localhost:8100/build/main.js:4272:62)
    at HomePage.initializeMap (http://localhost:8100/build/main.js:55716:19)
    at HomePage.loadMaps (http://localhost:8100/build/main.js:55636:18)
    at http://localhost:8100/build/main.js:55616:63
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8488)
    at c (http://localhost:8100/build/polyfills.js:3:12642)
    at http://localhost:8100/build/polyfills.js:3:13214
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9172)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4394:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9093)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:4349)
    at o (http://localhost:8100/build/polyfills.js:3:1437)
    at HTMLDocument.invoke (http://localhost:8100/build/polyfills.js:3:10190)
```

My files in home are basically all copied and pasted

Thank you

**Comment by Fiv38** [comment]
thank you daniel, but im still got error marker clusterer not defined, any solution for this error ?

i did add markerclusterer.js and in index.html edited the path file js.

thank you for this awesome maps :D

**Comment by danielehrhardt** [comment]
can you redownload the project and test it again?

**Comment by hanifmazlan** [comment]
same error i got

>core.js:1440 ERROR Error: Uncaught (in promise): ReferenceError: MarkerClusterer is not defined
ReferenceError: MarkerClusterer is not defined

**Comment by dreamdev21** [comment]
Same issue here.

**Comment by hichem-abdellali** [comment]
I solved it by including  `<script src="assets/js/markerclusterer_compiled.js"></script>` to the index.html the markerclusterer_compiled.js is available at [https://cdnjs.cloudflare.com/ajax/libs/js-marker-clusterer/1.0.0/markerclusterer_compiled.js]

**Comment by Hmerman6006** [comment]
Just add `'cluster' => false`.

**Comment by christopherduran** [comment]
Same issue, copy pasted!

**Comment by ctgs-sunily** [comment]
thank you [hichem-abdellali](https://github.com/hichem-abdellali)
